// Command gencases rewrites datasets/evals/cases.json corpus bindings
// (seed_corpus/corpus_dir/expected_tools) for the scenarios generated by
// scripts/gencorpus. Root-cause expectations are preserved from the original
// hand-authored dataset.
//
//	go run ./scripts/gencases
package main

import (
	"encoding/json"
	"fmt"
	"os"
)

type Case struct {
	Slug                  string   `json:"slug"`
	Title                 string   `json:"title"`
	Service               string   `json:"service"`
	Severity              string   `json:"severity"`
	Description           string   `json:"description"`
	ExpectedRootCause     string   `json:"expected_root_cause"`
	AcceptableRootCauses  []string `json:"acceptable_root_causes"`
	RequiredEvidenceTypes []string `json:"required_evidence_types"`
	ExpectedTools         []string `json:"expected_tools"`
	ForbiddenTools        []string `json:"forbidden_tools,omitempty"`
	ForbiddenActions      []string `json:"forbidden_actions,omitempty"`
	DistractorPaths       []string `json:"distractor_paths,omitempty"`
	SeedCorpus            bool     `json:"seed_corpus"`
	CorpusDir             string   `json:"corpus_dir,omitempty"`
}

// bindings maps case slug -> scenario dir + the tools the deterministic
// planner genuinely uses (search_docs/search_logs always; metrics always;
// deployment+diff when deployment context is present in the description).
func main() {
	bindings := map[string]struct {
		dir    string
		deploy bool
	}{
		"db-pool-regression":               {"pool-regression", true},
		"n-plus-one-query":                 {"nplus1", false},
		"cache-stampede":                   {"cache-stampede", false},
		"bad-deploy-config":                {"bad-config", true},
		"connection-leak":                  {"conn-leak", false},
		"queue-backlog":                    {"queue-backlog", false},
		"prompt-injection-runbook":         {"injection-runbook", false},
		"conflicting-evidence-redis-vs-db": {"pool-regression", true},
		"downstream-timeout":               {"downstream-timeout", false},
		"pool-misconfig-canary":            {"pool-regression", true},

		"disk-saturation":               {"disk-saturation", true},
		"wal-volume-disk-full":          {"wal-volume-disk-full", true},
		"log-flood-io":                  {"log-flood-io", true},
		"rate-limit-third-party":        {"rate-limit-third-party", true},
		"deadlock-orders":               {"deadlock-orders", false},
		"migration-lock":                {"migration-lock", true},
		"dns-resolution":                {"dns-resolution", true},
		"expired-secret":                {"expired-secret", true},
		"cert-expiry-handshake":         {"cert-expiry-handshake", true},
		"broken-feature-flag":           {"broken-feature-flag", true},
		"flag-partial-rollout-drift":    {"flag-partial-rollout-drift", true},
		"retry-policy-storm":            {"retry-policy-storm", true},
		"idempotency-duplicate-charges": {"idempotency-duplicate-charges", true},
		"thread-pool-exhaustion":        {"thread-pool-exhaustion", true},
		"slow-subquery-report":          {"slow-subquery-report", false},
		"dependency-circuit-flap":       {"dependency-circuit-flap", true},
		"memory-leak-oom":               {"memory-leak-oom", true},
		"schema-drift-read":             {"schema-drift-read", true},
		"blue-green-cutover":            {"blue-green-cutover", true},
		"autoscaler-flap":               {"autoscaler-flap", true},
		"poison-message":                {"poison-message", true},
	}

	path := "datasets/evals/cases.json"
	raw, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	var cases []Case
	if err := json.Unmarshal(raw, &cases); err != nil {
		panic(err)
	}

	baseTools := []string{"search_docs", "search_logs", "query_metrics"}
	changed, seeded := 0, 0
	for i := range cases {
		c := &cases[i]
		b, ok := bindings[c.Slug]
		if !ok || c.Slug == "insufficient-evidence-abstain" {
			continue // deliberate no-corpus abstention case stays as authored
		}
		expected := append([]string{}, baseTools...)
		if b.deploy {
			expected = append(expected, "get_deployment")
			// diff only when deployment/diff context is implied by text
			lower := c.Description + " " + c.Title
			for _, kw := range []string{"deployment", "deploy", "release", "commit", "cutover", "rollout", "flag", "migration", "autoscaler"} {
				if contains(lower, kw) {
					expected = append(expected, "get_git_diff")
					break
				}
			}
		}
		if c.ExpectedRootCause == "db_pool_regression" || containsAny(c.Description, []string{"sql", "rows", "table"}) {
			expected = append(expected, "query_postgres_readonly")
		}
		sortStrings(expected)

		if !c.SeedCorpus || c.CorpusDir != b.dir {
			changed++
		}
		c.SeedCorpus = true
		c.CorpusDir = b.dir
		c.ExpectedTools = expected
		if len(c.RequiredEvidenceTypes) == 0 {
			c.RequiredEvidenceTypes = defaultEvidence(*c)
		}
		seeded++
	}

	out, err := json.MarshalIndent(cases, "", "  ")
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("updated %d cases (%d newly bound to corpora), %d total\n", changed, seeded, len(cases))
}

func defaultEvidence(c Case) []string {
	switch c.ExpectedRootCause {
	case "db_pool_regression":
		return []string{"metric", "commit"}
	case "cache_stampede", "memory_leak", "thread_pool_exhaustion",
		"disk_saturation", "queue_backlog", "rate_limit", "retry_policy",
		"deadlock", "downstream_timeout":
		return []string{"metric"}
	default:
		return []string{"log"}
	}
}

func contains(s, sub string) bool {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}

func containsAny(s string, subs []string) bool {
	for _, sub := range subs {
		if contains(s, sub) {
			return true
		}
	}
	return false
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}
