package main

// allScenarios returns the full synthetic corpus. Keyword families are spread
// across log/metric/deployment/diff sources so single-file keyword matching is
// insufficient — correlation is required.
func allScenarios() []scenario {
	return []scenario{
		{
			slug: "disk-saturation", title: "API latency spikes correlate with disk usage alerts",
			service: "orders", severity: "sev2", metricSeries: "disk_used_pct",
			metricPoints: [][2]any{{"06:00", 71}, {"09:00", 88}, {"11:00", 98}},
			metricNote:   "disk usage climbed to 98% on the primary DB host; iowait spiked as the partition filled with WAL archive files; IO saturation degraded query latency across services.",
			logLines: []string{
				"2026-08-23T09:10:00Z orders WARN disk usage 91% on /var/lib/postgresql",
				"2026-08-23T09:40:00Z orders ERROR iowait 42% partition nearly full; queries queuing behind IO saturation",
				"2026-08-23T10:05:00Z orders WARN wal volume archive files accumulating faster than archiver removes them",
			},
			deployLine: "deployment service=orders commit 7a1b9c4d enabled debug WAL archiving every 30s (config change)",
			diffLine:   "commit 7a1b9c4d archive_command = 'cp %p /archive/%f' # archive lag risk when the wal volume fills",
		},
		{
			slug: "rate-limit-third-party", title: "Address validation failing intermittently",
			service: "checkout", severity: "sev3", metricSeries: "address_provider_429_rate",
			metricPoints: [][2]any{{"12:00", 2}, {"14:00", 18}, {"16:00", 41}},
			metricNote:   "third-party address provider returned 429 quota exceeded responses at 40/min after traffic growth; rate limit budget exhausted before daily reset.",
			logLines: []string{
				"2026-08-23T13:20:00Z checkout WARN address provider HTTP 429 quota exceeded (window remaining 0)",
				"2026-08-23T13:21:00Z checkout ERROR rate limit reached for provider account; retries amplify request volume",
				"2026-08-23T13:25:00Z checkout WARN backoff honored but quota already exhausted until midnight",
			},
			deployLine: "deployment service=checkout commit 5e6f7a8b switched address provider tier without raising rate limit quota",
			diffLine:   "commit 5e6f7a8b PROVIDER_TIER=standard # request volume doubled, quota unchanged -> 429 under load",
		},
		{
			slug: "deadlock-orders", title: "Order updates intermittently fail with serialization errors",
			service: "orders", severity: "sev3", metricSeries: "lock_wait_ms",
			metricPoints: [][2]any{{"08:00", 4}, {"12:00", 90}, {"15:00", 310}},
			metricNote:   "lock wait time climbing between order update transactions touching inventory rows in different order; deadlock detected every few minutes with serialization failure retries.",
			logLines: []string{
				"2026-08-23T12:44:00Z orders ERROR deadlock detected between txA(inventory->order) and txB(order->inventory)",
				"2026-08-23T12:45:00Z orders WARN serialization failure, retrying transaction (attempt 3); lock wait 280ms",
				"2026-08-23T12:52:00Z orders ERROR deadlock detected again on orders_pkey vs inventory_stock_idx",
			},
			deployLine: "deployment service=orders commit 9b8a7d6f reordered fulfillment transaction writes (schema unchanged)",
			diffLine:   "commit 9b8a7d6f fulfill(): UPDATE inventory BEFORE orders row lock # inconsistent lock ordering",
		},
		{
			slug: "dns-resolution", title: "Inventory service connection errors burst",
			service: "inventory", severity: "sev3", metricSeries: "dns_failures_per_min",
			metricPoints: [][2]any{{"07:00", 0}, {"07:30", 120}, {"08:00", 0}},
			metricNote:   "NXDOMAIN resolution failures burst after a DNS record TTL change; stale record cached by resolvers kept returning the retired IP; connection errors resolved after cache flush.",
			logLines: []string{
				"2026-08-23T07:31:00Z inventory ERROR dial tcp: lookup db-primary.internal: NXDOMAIN resolution failed",
				"2026-08-23T07:33:00Z inventory WARN resolver still serving stale record for db-primary.internal (old TTL 86400)",
				"2026-08-23T07:58:00Z inventory INFO dns cache flushed; connection errors stopped",
			},
			deployLine: "deployment service=inventory commit c1d2e3f4 DNS record TTL change 300->86400 during db failover",
			diffLine:   "commit c1d2e3f4 terraform: dns_ttl = 86400 # stale record pinned retired primary IP",
		},
		{
			slug: "expired-secret", title: "Auth service 401 wave",
			service: "payments", severity: "sev2", metricSeries: "auth_401_rate",
			metricPoints: [][2]any{{"01:50", 1}, {"02:05", 38}, {"03:00", 2}},
			metricNote:   "401 unauthorized surge began right after the provider credential secret expired at midnight per rotation policy notice; token expired signature on every attempt until rotation completed.",
			logLines: []string{
				"2026-08-23T02:00:11Z payments ERROR token expired for provider credential secret (rotation overdue)",
				"2026-08-23T02:00:12Z payments WARN upstream 401 unauthorized; credential expired per rotation policy notice",
				"2026-08-23T02:47:00Z payments INFO new secret deployed; 401 wave ended",
			},
			deployLine: "deployment service=payments commit f00dcafe rotated provider secret manually after expiry alert",
			diffLine:   "commit f00dcafe secrets/provider.token refreshed; adds rotation reminder cron",
		},
		{
			slug: "cert-expiry-handshake", title: "TLS handshake failures to inventory",
			service: "inventory", severity: "sev2", metricSeries: "tls_handshake_failures",
			metricPoints: [][2]any{{"23:45", 0}, {"00:05", 55}, {"01:00", 52}},
			metricNote:   "x509 certificate has expired errors between checkout and inventory; TLS handshake failures began exactly at midnight when the leaf certificate validity ended; rotation job had failed silently last week.",
			logLines: []string{
				"2026-08-23T00:01:00Z inventory ERROR remote error: tls: failed to verify certificate: x509 certificate has expired",
				"2026-08-23T00:03:00Z inventory WARN cert rotation job failed silently last week (cron exit code 1 unmonitored)",
				"2026-08-23T00:30:00Z inventory ERROR handshake still failing; credential expired chain presented to peers",
			},
			deployLine: "deployment service=inventory commit ab12cd34 replaced leaf certificate after alert page",
			diffLine:   "commit ab12cd34 certs/inventory-leaf.pem renewed; add expiry monitoring",
		},
		{
			slug: "broken-feature-flag", title: "New checkout flow errors for 10% of users",
			service: "checkout", severity: "sev2", metricSeries: "checkout_error_rate",
			metricPoints: [][2]any{{"09:00", 0.2}, {"10:00", 9.8}, {"11:00", 0.3}},
			metricNote:   "error rate correlates exactly with the flag cohort: feature flag enabled a defective code path for rollout percentage 10; rollback of the flag fixed errors immediately.",
			logLines: []string{
				"2026-08-23T09:58:00Z checkout INFO feature flag new_checkout_flow enabled for rollout percentage 10",
				"2026-08-23T10:04:00Z checkout ERROR nil map access in new flow path (defective code path), errors only for flagged users",
				"2026-08-23T10:41:00Z checkout INFO flag rolled back to control cohort; error rate normalized",
			},
			deployLine: "deployment service=checkout commit dd22ee44 flag config change: new_checkout_flow 0%->10%",
			diffLine:   "commit dd22ee44 flags.yaml new_checkout_flow.rollout=10 # defective handler behind flag",
		},
		{
			slug: "flag-partial-rollout-drift", title: "Feature state inconsistent across regions",
			service: "checkout", severity: "sev3", metricSeries: "flag_eval_divergence",
			metricPoints: [][2]any{{"11:00", 0}, {"13:00", 7}, {"17:00", 7}},
			metricNote:   "flag evaluation differs across regions because one regional config watcher is stale; rollout percentage drifted by 6 points; users see inconsistent experience depending on edge region.",
			logLines: []string{
				"2026-08-23T12:50:00Z checkout WARN regional watcher eu-west lagging 40m behind flag distribution",
				"2026-08-23T12:51:00Z checkout ERROR stale rollout percentage served from drifted region cache (feature flag mismatch)",
				"2026-08-23T16:59:00Z checkout INFO watcher restarted; drift closed",
			},
			deployLine: "deployment service=checkout commit ee55aa77 bumped rollout to 24% only where watchers healthy",
			diffLine:   "commit ee55aa77 flagsync: warn if regional watcher lag > 60s (was missing)",
		},
		{
			slug: "retry-policy-storm", title: "Self-inflicted traffic amplification during incident",
			service: "notifications", severity: "sev2", metricSeries: "retry_multiplier",
			metricPoints: [][2]any{{"18:00", 1.1}, {"18:30", 4.2}, {"19:00", 8.4}},
			metricNote:   "retries exceeded the configured budget because backoff was disabled in the new client; retry storm amplified load 8x against an already struggling dependency; max retry removed accidentally.",
			logLines: []string{
				"2026-08-23T18:22:00Z notifications WARN retries exceeded budget (attempt 9/3); backoff disabled by client upgrade",
				"2026-08-23T18:31:00Z notifications ERROR retry storm detected: outbound qps 8x baseline, max retry unset",
				"2026-08-23T19:02:00Z notifications INFO client downgraded; amplification stopped",
			},
			deployLine: "deployment service=notifications commit bb99cc11 upgraded notification SDK (config change: retry defaults)",
			diffLine:   "commit bb99cc11 sdk.retry.max_retries = unlimited # backoff disabled by default in v3",
		},
		{
			slug: "idempotency-duplicate-charges", title: "Duplicate payment captures after client retry",
			service: "payments", severity: "sev1", metricSeries: "duplicate_charge_rate",
			metricPoints: [][2]any{{"20:00", 0}, {"21:00", 3.1}, {"23:00", 2.8}},
			metricNote:   "client retried capture without an idempotency key after gateway timeouts; duplicate charges posted because the dedup window missed the retry path that the SDK upgrade re-introduced.",
			logLines: []string{
				"2026-08-23T20:58:00Z payments WARN capture attempt retried without idempotency key header present",
				"2026-08-23T20:59:00Z payments ERROR duplicate charges posted for order (dedup window miss on retry path)",
				"2026-08-23T22:30:00Z payments INFO max retry restored and key enforced; duplicates ceased",
			},
			deployLine: "deployment service=payments commit ca11ef12 payment SDK upgrade changed retry semantics (max retry removed)",
			diffLine:   "commit ca11ef12 capture(): idempotency_key omitted on automatic retry path",
		},
		{
			slug: "thread-pool-exhaustion", title: "Checkout worker threads starved under flash sale load",
			service: "checkout", severity: "sev2", metricSeries: "thread_pool_active_pct",
			metricPoints: [][2]any{{"16:00", 55}, {"17:30", 97}, {"18:00", 100}},
			metricNote:   "thread pool exhausted during flash sale: queue rejection rate climbed as worker threads blocked on slow external call without timeout, starving other requests.",
			logLines: []string{
				"2026-08-23T17:20:00Z checkout WARN thread pool exhausted (active 100%); queue rejection rate climbing",
				"2026-08-23T17:26:00Z checkout ERROR worker threads blocked on tax-provider call with no timeout set",
				"2026-08-23T18:05:00Z checkout INFO pool sized up + timeout added; starvation cleared",
			},
			deployLine: "deployment service=checkout commit de11ad22 raised pool size but left external call timeout unset",
			diffLine:   "commit de11ad22 TaxClient: connect+read timeout MISSING # threads block indefinitely",
		},
		{
			slug: "slow-subquery-report", title: "Reporting query saturates read pool",
			service: "orders", severity: "sev3", metricSeries: "read_replica_load_pct",
			metricPoints: [][2]any{{"05:00", 40}, {"06:00", 88}, {"08:00", 95}},
			metricNote:   "new reporting dashboard runs a cartesian join subquery with sequential scans saturating read replicas; query lacks index and filters rows late, multiplying work per item.",
			logLines: []string{
				"2026-08-23T06:12:00Z orders WARN slow query: SELECT ... FROM order_items JOIN reports_batch sequential scan (no index)",
				"2026-08-23T06:14:00Z orders ERROR cartesian join detected in report subquery; repeated select per report row",
				"2026-08-23T08:00:00Z orders INFO dashboard query rewritten with index and late filtering",
			},
			deployLine: "deployment service=orders commit ff66aa33 shipped analytics dashboard v1 (reporting query regression)",
			diffLine:   "commit ff66aa33 reports.sql: correlated subquery per row # missing index on order_items(report_id)",
		},
		{
			slug: "dependency-circuit-flap", title: "Circuit breaker flaps between states",
			service: "payments", severity: "sev3", metricSeries: "breaker_transitions_per_min",
			metricPoints: [][2]any{{"10:00", 1}, {"12:00", 22}, {"14:00", 19}},
			metricNote:   "circuit opens and closes rapidly because half-open probe concurrency is too aggressive while downstream latency stays elevated; breaker settings tuned for faster recovery than the provider supports.",
			logLines: []string{
				"2026-08-23T11:58:00Z payments WARN circuit open toward settlement-provider (downstream latency p99 4.1s)",
				"2026-08-23T11:59:00Z payments INFO half-open probes x20 concurrent; circuit closes then immediately opens again — flapping",
				"2026-08-23T13:40:00Z payments WARN breaker settings mismatched with provider recovery speed",
			},
			deployLine: "deployment service=payments commit cb77aa21 breaker tuning change (probe concurrency 3->20)",
			diffLine:   "commit cb77aa21 breaker.half_open_max_probes = 20 # faster recovery than provider supports",
		},
		{
			slug: "memory-leak-oom", title: "Inventory pods restart nightly",
			service: "inventory", severity: "sev2", metricSeries: "rss_mb",
			metricPoints: [][2]any{{"00:00", 210}, {"12:00", 480}, {"23:00", 1020}},
			metricNote:   "memory grows steadily until OOMKill around 03:00 nightly; heap profile shows growing per-request map retention introduced by the latest release (leak introduced in serializer).",
			logLines: []string{
				"2026-08-23T02:57:00Z inventory ERROR OOMKilled: memory limit exceeded (rss 1019MiB / limit 1GiB)",
				"2026-08-23T02:57:01Z inventory WARN heap profile shows growing cache without eviction since latest release",
				"2026-08-23T14:00:00Z inventory INFO leak reproduced locally: per-request map never evicted (memory grows steadily)",
			},
			deployLine: "deployment service=inventory commit ea55bb99 released serializer v2 (leak introduced here)",
			diffLine:   "commit ea55bb99 serialize(): append to request-scoped map without eviction # retention grows",
		},
		{
			slug: "wal-volume-disk-full", title: "Writes stall on orders primary",
			service: "orders", severity: "sev1", metricSeries: "pg_wal_volume_pct",
			metricPoints: [][2]any{{"04:00", 61}, {"06:00", 93}, {"06:40", 100}},
			metricNote:   "WAL accumulation filled the pg_wal volume; checkpoints throttled writes while archiver lagged after a network interruption to the archive target; disk saturation on the wal partition stalled commits.",
			logLines: []string{
				"2026-08-23T06:10:00Z orders ERROR pg_wal volume 96% full; checkpoints throttling writes",
				"2026-08-23T06:12:00Z orders WARN archiver lagged 14GB after network interruption to archive target (wal accumulation)",
				"2026-08-23T06:39:00Z orders ERROR disk saturation on wal partition; commits stalled",
			},
			deployLine: "deployment service=orders commit aa77ee31 moved archive target to secondary site (network path change)",
			diffLine:   "commit aa77ee31 archive target = archive2.site # single NIC, no retry buffer on interruption",
		},
		{
			slug: "schema-drift-read", title: "Analytics reads fail with unknown column",
			service: "orders", severity: "sev4", metricSeries: "replica_lag_seconds",
			metricPoints: [][2]any{{"09:00", 2}, {"10:00", 180}, {"12:00", 0}},
			metricNote:   "reader replica has schema drift: column added on primary missing on lagging replica; replication SQL conflict halts replay and reads hitting the stale replica fail with unknown column errors.",
			logLines: []string{
				"2026-08-23T09:47:00Z orders ERROR replica apply: replication conflict on ALTER TABLE (schema drift detected)",
				"2026-08-23T09:48:00Z orders ERROR analytics reads fail: column \"discount_code\" unknown column on replica",
				"2026-08-23T11:58:00Z orders INFO replica resynced; replay resumed",
			},
			deployLine: "deployment service=orders commit cc31dd41 deployed migration adding discount_code before replica resync",
			diffLine:   "commit cc31dd41 migrations/0042_add_discount_code.sql # non-concurrent deploy order",
		},
		{
			slug: "migration-lock", title: "Deploy hung acquiring schema lock",
			service: "orders", severity: "sev2", metricSeries: "access_exclusive_wait_ms",
			metricPoints: [][2]any{{"03:00", 0}, {"03:20", 420000}, {"04:00", 900000}},
			metricNote:   "migration transaction held ACCESS EXCLUSIVE lock on the orders table for minutes; queries queued behind the lock while deploy automation ran a long-running index build inside the same transaction (lock wait cascade).",
			logLines: []string{
				"2026-08-23T03:14:00Z orders WARN ACCESS EXCLUSIVE lock held by migration for 240s; queries queued behind lock",
				"2026-08-23T03:16:00Z orders ERROR lock wait cascade: 800 sessions waiting on OrdersIdxBuild",
				"2026-08-23T03:59:00Z orders INFO migration killed; long-running index build moved out of transaction",
			},
			deployLine: "deployment service=orders commit dd88ff22 migration runner change allowed DDL inside app transaction",
			diffLine:   "commit dd88ff22 migrate(): CREATE INDEX CONCURRENTLY inside BEGIN # not concurrent, holds exclusive lock",
		},
		{
			slug: "blue-green-cutover", title: "Errors burst during traffic switch",
			service: "checkout", severity: "sev2", metricSeries: "connection_reset_rate",
			metricPoints: [][2]any{{"22:50", 0}, {"23:00", 340}, {"23:10", 12}},
			metricNote:   "blue-green cutover drained the old pool too fast: drain seconds misconfigured far below keep-alive lifetime produced connection reset storms at the load balancer during the switch window.",
			logLines: []string{
				"2026-08-23T22:59:40Z checkout ERROR connection reset by peer during blue-green cutover (drain too fast)",
				"2026-08-23T22:59:55Z checkout WARN reset storms at LB: old pool drained in 5s while keep-alive 65s (misconfigured drain seconds)",
				"2026-08-23T23:09:00Z checkout INFO cutover completed; resets stopped",
			},
			deployLine: "deployment service=checkout commit ef01ab23 cutover automation change (drain seconds lowered)",
			diffLine:   "commit ef01ab23 cutover.drain_seconds = 5 # below keep-alive idle 65s -> reset storms",
		},
		{
			slug: "autoscaler-flap", title: "Checkout capacity oscillates wildly",
			service: "checkout", severity: "sev3", metricSeries: "replica_count",
			metricPoints: [][2]any{{"14:00", 8}, {"14:10", 26}, {"14:20", 9}, {"14:30", 28}},
			metricNote:   "autoscaler flapping between min and max replicas due to metric feedback delay: scale-up arrives after traffic passed and scale-down triggers mid-spike because the config change reduced stabilization window to zero.",
			logLines: []string{
				"2026-08-23T14:08:00Z checkout WARN scale-up arrived 90s after spike (metric feedback delay)",
				"2026-08-23T14:18:00Z checkout ERROR scale-down triggered mid-spike; capacity oscillation visible in metrics",
				"2026-08-23T14:29:00Z checkout WARN autoscaler config change removed stabilization window entirely",
			},
			deployLine: "deployment service=checkout commit fe21dc10 autoscaler policy update (config change)",
			diffLine:   "commit fe21dc10 hpa.stabilization_window = 0 # flapping between min and max replicas",
		},
		{
			slug: "log-flood-io", title: "Debug logging floods disk during peak",
			service: "notifications", severity: "sev3", metricSeries: "log_write_mbps",
			metricPoints: [][2]any{{"15:00", 4}, {"17:00", 120}, {"19:00", 130}},
			metricNote:   "debug level logging enabled by default in the release flooded disk with log writes; iowait spiked matching bursts and the volume filled during peak hours (log flood saturated io).",
			logLines: []string{
				"2026-08-23T16:40:00Z notifications WARN debug level logging enabled by default in release build (log flood begins)",
				"2026-08-23T16:55:00Z notifications ERROR iowait spikes match log write bursts; disk saturation imminent",
				"2026-08-23T18:50:00Z notifications INFO level reverted to info; flood stopped",
			},
			deployLine: "deployment service=notifications commit ba11db33 release build flipped default log level (config change)",
			diffLine:   "commit ba11db33 logger.default_level = debug # floods disk at peak write volume",
		},
		{
			slug: "poison-message", title: "Notification consumer crashes on single message",
			service: "notifications", severity: "sev3", metricSeries: "redelivery_loop_count",
			metricPoints: [][2]any{{"08:00", 0}, {"09:00", 1400}, {"11:00", 5200}},
			metricNote:   "one malformed payload acts as poison pill: consumer crashes and redelivers the same message forever because DLQ policy missing, so redelivery loops consume the whole consumer group budget (backlog rising).",
			logLines: []string{
				"2026-08-23T08:57:00Z notifications ERROR consumer panic on malformed payload (poison message); process restart loop",
				"2026-08-23T08:58:00Z notifications WARN redelivery loop: same offset reprocessed 400x; DLQ policy missing",
				"2026-08-23T10:59:00Z notifications INFO poison message quarantined to dead letter queue",
			},
			deployLine: "deployment service=notifications commit ac13df24 consumer v2 skipped DLQ wiring (queue backlog risk)",
			diffLine:   "commit ac13df24 consumer: dlq_topic removed from config # malformed payload loops forever",
		},
	}
}
